package org.domain.rules;

dialect "mvel"

import eu.ohim.sp.core.domain.validation.ErrorCore;
import eu.ohim.sp.core.domain.validation.ErrorList;
import eu.ohim.sp.core.domain.design.Design;
import eu.ohim.sp.core.domain.design.DesignApplication;
import eu.ohim.sp.core.domain.validation.RulesInformation;
import eu.ohim.sp.core.domain.payment.FeeList;
import eu.ohim.sp.core.domain.payment.FeeType;
import eu.ohim.sp.core.domain.payment.Fee;
import eu.ohim.sp.core.domain.resources.DocumentKind;
import eu.ohim.sp.core.domain.resources.Document;
import java.util.Map;
import java.util.HashMap;
import java.util.TreeMap;
import java.util.List;
import java.util.Date;
import java.util.Calendar;
import java.text.DecimalFormat;
import org.apache.log4j.Logger;

rule "Fees reader"
salience 1000
no-loop
    when
		FeeList($feeTypeList : feeTypeList)
        $bF : FeeType("basicFee".equals(nameKey)) from $feeTypeList
    then
    	TreeMap map = new TreeMap();
        map.put("basicFee", $bF);
        insert(map);
end

rule "Basic Fee"
no-loop
    when
        $results : HashMap()
        $map : TreeMap()
    then
        # Creates the base fee.
        Fee fee = new Fee();
        fee.setFeeType((FeeType) $map.get("basicFee"));
        fee.setQuantity(1);
        fee.setUnitAmount(((FeeType) $map.get("basicFee")).getDefaultValue());
        fee.setAmount(fee.quantity * fee.unitAmount);
        # Adds the base fee to the result list
        $results.put("basicFee", fee);
end


//generates unique ids for the fees and also references the trademark to which the fee applies
//tradeMark is null when the fee is general, not trademark dependant
function String generateUID(Fee fee, DesignApplication designApplication){
	String designId = "";
	String designPOZ = "";
	if(designApplication != null){
		designId = designApplication.getDesignDetails().get(0).getDesignIdentifier() + "|";
		designPOZ = designApplication.getDesignDetails().get(0).getDesignIdentifier();
		if (designPOZ == null || designPOZ == "")
			designPOZ = designApplication.getDesignDetails().get(0).getRegistrationNumber();
	}
	fee.setStatus(designPOZ);
	return designId + fee.toString();
}