package org.domain.rules;
dialect "mvel"

import eu.ohim.sp.core.domain.validation.ApplicationIdentifier;
import eu.ohim.sp.core.domain.validation.RulesInformation;
import java.util.HashMap;

rule "Identifier Creator"
salience 1000
no-loop
    when
        $map : HashMap()
        ApplicationIdentifier($office : office, $year : year, $code : code)
        eval($office != null  && $year != null && $code != null &&
             $office != "" && $year != "" && $code != "")
    then
        int value = Integer.parseInt($code);
        String codeFormatted = String.format("%011d", (int) value);
        String finalId = "EF" + $office + $year + codeFormatted;
        $map.put("provisionalId", finalId);
end
