package org.domain.rules;

dialect "mvel"

import eu.ohim.sp.core.domain.validation.ErrorCore;
import eu.ohim.sp.core.domain.validation.ErrorList;
import eu.ohim.sp.core.domain.design.Design;
import eu.ohim.sp.core.domain.design.DesignApplication;
import eu.ohim.sp.core.domain.validation.RulesInformation;
import eu.ohim.sp.core.domain.payment.FeeList;
import eu.ohim.sp.core.domain.payment.FeeType;
import eu.ohim.sp.core.domain.payment.Fee;
import eu.ohim.sp.core.domain.resources.DocumentKind;
import eu.ohim.sp.core.domain.resources.Document;
import java.util.Map;
import java.util.HashMap;
import java.util.TreeMap;
import java.util.List;
import java.util.Date;
import java.util.Calendar;
import java.text.DecimalFormat;
import org.apache.log4j.Logger;
import eu.ohim.sp.core.domain.design.DesignApplication;
import eu.ohim.sp.core.domain.application.EServiceApplication;
import eu.ohim.sp.core.domain.person.PersonChange;
import eu.ohim.sp.core.domain.person.PersonChangeKind;
import java.lang.*;

rule "Fees reader"
salience 1000
no-loop
    when
		FeeList($feeTypeList : feeTypeList)
        $basic : FeeType("basicFee".equals(nameKey)) from $feeTypeList

    then
    	TreeMap map = new TreeMap();
        map.put("basicFee", $basic);

        insert(map);
end

rule "Basic Fee"
no-loop
    when
        $results : HashMap()
        $map : TreeMap()
		EServiceApplication()
    then
        FeeType feeType = (FeeType) $map.get("basicFee");
        // Do not create fee if value is 0

            # Creates the base fee
        Fee fee = new Fee();
        fee.setFeeType(feeType);
        fee.setQuantity(1);
        fee.setUnitAmount(feeType.getDefaultValue());
        fee.setAmount(fee.quantity * fee.unitAmount);
            # Adds the base fee to the result list
        $results.put("basicFee", fee);

end
