/*******************************************************************************
 * * $Id:: PaymentKind.java 18155 2012-12-14 08:59:24Z virgida $
 * * . * .
 * * * RRRR * Copyright © 2012 OHIM: Office for Harmonization
 * * . RR R . in the Internal Market (trade marks and designs)
 * * * RRR *
 * * . RR RR . ALL RIGHTS RESERVED
 * * * . _ . *
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.23 at 10:29:04 AM CEST 
//

package eu.ohim.sp.core.domain.payment;

import java.io.Serializable;

/**
 * @author soriama
 * 
 */
@Deprecated
public enum FeeIdentifierKind implements Serializable {

    TOTAL_FEE("TOTAL_FEE"), BASIC_FEE("BASIC_FEE"), COLLECTIVE_FEE("COLLECTIVE_FEE"), EXTRA_CLASS_FEE_BASIC(
            "EXTRA_CLASS_FEE_BASIC"), EXTRA_CLASS_FEE_COLLECTIVE("EXTRA_CLASS_FEE_COLLECTIVE"), NATIONAL_SEARCH_FEE(
            "NATIONAL_SEARCH_FEE"), ONLINE_APP_DISCOUNT("ONLINE_APP_DISCOUNT");

    private FeeIdentifierKind(final String text) {
        this.text = text;
    }

    private final String text;

    @Override
    public String toString() {
        return text;
    }

}
