/*******************************************************************************
 * * $Id:: PaymentKind.java 121785 2013-06-06 18:45:12Z karalch                  $
 * *       . * .
 * *     * RRRR  *    Copyright © 2012 OHIM: Office for Harmonization
 * *   .   RR  R   .  in the Internal Market (trade marks and designs)
 * *   *   RRR     *
 * *    .  RR RR  .   ALL RIGHTS RESERVED
 * *     * . _ . *
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.23 at 10:29:04 AM CEST 
//


package eu.ohim.sp.core.domain.payment;

import java.io.Serializable;


/**
 * @author soriama
 *
 */
public enum PaymentKind implements Serializable {

	CREDIT_CARD("Credit Card"),
    BANK_TRANSFER("Bank Transfer"),
    DEBIT_CARD("Debit Card"),
    ONLINE_PAYMENT("Online Payment"),
    POSTAL_ORDER("Postal Order"),
    CURRENT_ACCOUNT("Current Account"),
    OTHER("Other");
	
	private PaymentKind(final String value) {
		this.value = value;
	}

	private final String value;

	public String value() {
		return value;
	}	
}
