package eu.ohim.sp.core.fee.provided;

import eu.ohim.sp.external.services.fee.FeeFault;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-03-17T10:46:58.704+01:00
 * Generated source version: 2.5.1
 */

@WebFault(name = "feeFault", targetNamespace = "http://ohim.eu/fsp/services/feemanagement/v3")
public class FeeFault_Exception extends Exception {

    private FeeFault feeFault;

    public FeeFault_Exception() {
        super();
    }

    public FeeFault_Exception(String message) {
        super(message);
    }

    public FeeFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public FeeFault_Exception(String message, FeeFault feeFault) {
        super(message);
        this.feeFault = feeFault;
    }

    public FeeFault_Exception(String message, FeeFault feeFault, Throwable cause) {
        super(message, cause);
        this.feeFault = feeFault;
    }

    public FeeFault getFaultInfo() {
        return this.feeFault;
    }
}
