package org.domain.rules;
dialect "mvel"

import java.util.Map;
import java.util.List;
import java.util.ArrayList;
import org.apache.commons.lang.StringUtils;
import eu.ohim.sp.core.domain.validation.ErrorList;
import eu.ohim.sp.core.domain.person.Representative;
import eu.ohim.sp.core.domain.person.PersonIdentifier;
import eu.ohim.sp.core.configuration.domain.xsd.Field;
import eu.ohim.sp.core.configuration.domain.xsd.Section;
import eu.ohim.sp.core.domain.validation.RulesInformation;
import eu.ohim.sp.core.domain.person.RepresentativeKind
import eu.ohim.sp.core.domain.person.PersonKind;
import java.util.HashMap
import java.util.Date;

global eu.ohim.sp.core.domain.validation.ErrorList errorList;


rule "BR type - Empty"
salience 1000
when
	$errorList : ErrorList()
	Section( $fields : field )
	Field( id == "type", $fieldUsable : usable, $fieldRequired : required ) from $fields
	eval($fieldUsable == true && $fieldRequired == true)
	Representative(kind==null)
	$rulesInformation : RulesInformation($customObjects : customObjects )
then
	HashMap co = $customObjects;
	Boolean imported = co.get("imported");
	Boolean isSectionValidation = co.get("isSectionValidation");

	if (isSectionValidation == false){
		addError("type", "BRMandatory", "This field is mandatory", null, $errorList);
	}else{
		addError(null, "BR.representative.type.Empty", "The representative type field is mandatory", "mainForm.representativeDataSection", $errorList);
	}

end

rule "BR afimi- Empty Array"
salience 1000
when
	$errorList : ErrorList()
	Section( $fields : field, $validateImport : validateImport  )
	Field( id == "personIdentifierForm.afimi", $fieldUsable : usable, $fieldRequired : required) from $fields
	eval($fieldUsable == true && $fieldRequired == true)
	Representative(identifiers == null || (identifiers != null && identifiers.size() == 0))
	$rulesInformation : RulesInformation($customObjects : customObjects )
then
	HashMap co = $customObjects;
	Boolean imported = co.get("imported");
	Boolean isSectionValidation = co.get("isSectionValidation");

    if ((imported == false || $validateImport == true) && isSectionValidation == false){
        addError("personIdentifierForm.afimi", "BRMandatory", "This field is mandatory", null, $errorList);
    }else if((imported == false || $validateImport == true) && isSectionValidation == true){
        addError(null, "BR.representative.afimi.Empty", "The Afimi field is mandatory.", "mainForm.representativeDataSection", $errorList);
    }
end

rule "BR afimi- Empty"
salience 1000
when
	$errorList : ErrorList()
	Section( $fields : field, $validateImport : validateImport  )
	Field( id == "personIdentifierForm.afimi", $fieldUsable : usable, $fieldRequired : required) from $fields
	eval($fieldUsable == true && $fieldRequired == true)
	Representative(identifiers != null, $identifiers : identifiers)
    PersonIdentifier(StringUtils.isNotEmpty(identifierKindCode),
                     identifierKindCode.equals("VAT Number"),
                     StringUtils.isEmpty(value)) from $identifiers
	$rulesInformation : RulesInformation($customObjects : customObjects )
then
	HashMap co = $customObjects;
	Boolean imported = co.get("imported");
	Boolean isSectionValidation = co.get("isSectionValidation");

    if ((imported == false || $validateImport == true) && isSectionValidation == false){
        addError("personIdentifierForm.afimi", "BRMandatory", "This field is mandatory", null, $errorList);
    }else if((imported == false || $validateImport == true) && isSectionValidation == true){
        addError(null, "BR.representative.afimi.Empty", "The Afimi field is mandatory.", "mainForm.representativeDataSection", $errorList);
    }
end

rule "BR afimi - Format"
salience 1000
when
	$errorList : ErrorList()
	Section( $fields : field, $validateImport : validateImport  )
	Field( id == "personIdentifierForm.afimi", $fieldUsable : usable, $regex : format) from $fields
	eval($fieldUsable == true && StringUtils.isNotEmpty($regex))
	Representative(identifiers != null, $identifiers : identifiers)
    PersonIdentifier(StringUtils.isNotEmpty(identifierKindCode),
                     identifierKindCode.equals("VAT Number"),
                     StringUtils.isNotEmpty(value),
                     value not matches $regex) from $identifiers
	$rulesInformation : RulesInformation($customObjects : customObjects )
then
	HashMap co = $customObjects;
	Boolean imported = co.get("imported");
	Boolean isSectionValidation = co.get("isSectionValidation");

	if ((imported == false || $validateImport == true) && isSectionValidation == false){
        addError("personIdentifierForm.afimi", "BRFormat", "This field has a bad format", null, $errorList);
    }else if((imported == false || $validateImport == true) && isSectionValidation == true){
        addError(null, "BR.representative.afimi.Format", "The Afimi field has a bad format.", "mainForm.representativeDataSection", $errorList);
    }
end

rule "BR DOY- Empty Array"
salience 1000
when
	$errorList : ErrorList()
	Section( $fields : field, $validateImport : validateImport  )
	Field( id == "personIdentifierForm.doy", $fieldUsable : usable, $fieldRequired : required) from $fields
	eval($fieldUsable == true && $fieldRequired == true)
	Representative(identifiers == null || (identifiers != null && identifiers.size() == 0))
	$rulesInformation : RulesInformation($customObjects : customObjects )
then
	HashMap co = $customObjects;
	Boolean imported = co.get("imported");
	Boolean isSectionValidation = co.get("isSectionValidation");

    if ((imported == false || $validateImport == true) && isSectionValidation == false){
        addError("personIdentifierForm.doy", "BRMandatory", "This field is mandatory", null, $errorList);
    }else if((imported == false || $validateImport == true) && isSectionValidation == true){
        addError(null, "BR.representative.doy.Empty", "The Doy field is mandatory.", "mainForm.representativeDataSection", $errorList);
    }
end

rule "BR DOY - Empty"
salience 1000
when
	$errorList : ErrorList()
	Section( $fields : field, $validateImport : validateImport  )
	Field( id == "personIdentifierForm.doy", $fieldUsable : usable, $fieldRequired : required) from $fields
	eval($fieldUsable == true && $fieldRequired == true)
	Representative(identifiers != null, $identifiers : identifiers)
    PersonIdentifier(StringUtils.isNotEmpty(identifierKindCode),
                     identifierKindCode.equals("Tax Office"),
                     StringUtils.isEmpty(value)) from $identifiers
	$rulesInformation : RulesInformation($customObjects : customObjects )
then
	HashMap co = $customObjects;
	Boolean imported = co.get("imported");
	Boolean isSectionValidation = co.get("isSectionValidation");

    if ((imported == false || $validateImport == true) && isSectionValidation == false){
        addError("personIdentifierForm.doy", "BRMandatory", "This field is mandatory", null, $errorList);
    }else if((imported == false || $validateImport == true) && isSectionValidation == true){
        addError(null, "BR.representative.doy.Empty", "The Doy field is mandatory.", "mainForm.representativeDataSection", $errorList);
    }
end

rule "BR DOY - Format"
salience 1000
when
	$errorList : ErrorList()
	Section( $fields : field, $validateImport : validateImport  )
	Field( id == "personIdentifierForm.doy", $fieldUsable : usable, $regex : format) from $fields
	eval($fieldUsable == true && StringUtils.isNotEmpty($regex))
	Representative(identifiers != null, $identifiers : identifiers)
    PersonIdentifier(StringUtils.isNotEmpty(identifierKindCode),
                     identifierKindCode.equals("Tax Office"),
                     StringUtils.isNotEmpty(value),
                     value not matches $regex) from $identifiers
	$rulesInformation : RulesInformation($customObjects : customObjects )
then
	HashMap co = $customObjects;
	Boolean imported = co.get("imported");
	Boolean isSectionValidation = co.get("isSectionValidation");

	if ((imported == false || $validateImport == true) && isSectionValidation == false){
        addError("personIdentifierForm.doy", "BRFormat", "This field has a bad format", null, $errorList);
    }else if((imported == false || $validateImport == true) && isSectionValidation == true){
        addError(null, "BR.representative.doy.Format", "The Doy field has a bad format.", "mainForm.representativeDataSection", $errorList);
    }
end

rule "BR Nationality - Empty"
salience 1000
when
	$errorList : ErrorList()
	Section( $fields : field, $validateImport : validateImport  )
	Field( id == "nationality", $fieldUsable : usable, $fieldRequired : required) from $fields
	eval($fieldUsable == true && $fieldRequired == true)
	Representative(nationality == null || nationality == "Unidentified" || StringUtils.isEmpty(nationality)==true)
	$rulesInformation : RulesInformation($customObjects : customObjects )
then
	HashMap co = $customObjects;

	Boolean imported = co.get("imported");
	Boolean isSectionValidation = co.get("isSectionValidation");

	if (isSectionValidation == false){
		addError("nationality",	 "BRMandatory", "This field is mandatory",	 null,	$errorList);
	}else if(isSectionValidation == true){
		addError(null, "BR.representative.nationality.Empty", "The nationality field is mandatory.", "mainForm.representativeDataSection", $errorList);
	}
end

rule "BR(legal entity) organization name - Empty"
salience 1000
when
	$errorList : ErrorList()
	Section( $fields : field, $validateImport : validateImport  )
	Field( id == "nameOfLegalEntity", $fieldUsable : usable, $fieldRequired : required) from $fields
	eval($fieldUsable == true && $fieldRequired == true)
	Representative( name==null || (name != null && (StringUtils.isEmpty(name.organizationName)) ))
	$rulesInformation : RulesInformation($customObjects : customObjects )
then
	HashMap co = $customObjects;
	Boolean imported = co.get("imported");
	Boolean isSectionValidation = co.get("isSectionValidation");

	if ((imported == false || $validateImport == true) && isSectionValidation == false){
		addError("nameOfLegalEntity", "BRMandatory", "This field is mandatory", null, $errorList);
	}else if((imported == false || $validateImport == true) && isSectionValidation == true){
		addError(null, "BR.representative.legalEntity.organizationName.Empty", "The Organization Name field is mandatory", "mainForm.representativeDataSection", $errorList);
	}
end

rule "BR(legal entity) organization name - Content"
salience 1000
when
	$errorList : ErrorList()
	Section( $fields : field, $validateImport : validateImport  )
	Field( id == "nameOfLegalEntity", $fieldUsable : usable, $regex : format) from $fields
	eval($fieldUsable == true && StringUtils.isNotEmpty($regex))
	Representative(name != null &&
	          StringUtils.isNotEmpty(name.organizationName) &&
	          name.organizationName not matches $regex)
	$rulesInformation : RulesInformation($customObjects : customObjects )
then
	HashMap co = $customObjects;
	Boolean imported = co.get("imported");
	Boolean isSectionValidation = co.get("isSectionValidation");

	if ((imported == false || $validateImport == true) && isSectionValidation == false){
		addError("nameOfLegalEntity", "BRFormat", "This field has a bad format", null, $errorList);
	}else if((imported == false || $validateImport == true) && isSectionValidation == true){
		addError(null, "BR.representative.legalEntity.organizationName.Format", "The organization name field has a bad format", "mainForm.representativeDataSection", $errorList);
	}
end

rule "BR(legal entity) legal form - Empty"
salience 1000
when
	$errorList : ErrorList()
	Section( $fields : field, $validateImport : validateImport  )
	Field( id == "legalForm", $fieldUsable : usable, $fieldRequired : required) from $fields
	eval($fieldUsable == true && $fieldRequired == true)
	Representative((legalForm==null) ||(legalForm != null && StringUtils.isEmpty(legalForm)))
	$rulesInformation : RulesInformation($customObjects : customObjects )
then
	HashMap co = $customObjects;
	Boolean imported = co.get("imported");
	Boolean isSectionValidation = co.get("isSectionValidation");

	if ((imported == false || $validateImport == true) && isSectionValidation == false){
		addError("legalForm", "BRMandatory", "This field is mandatory", null, $errorList);
	}else if((imported == false || $validateImport == true) && isSectionValidation == true){
		addError(null, "BR.representative.legalEntity.legalForm.Empty", "The Legal Form field is mandatory", "mainForm.representativeDataSection", $errorList);
	}
end

rule "BR(legal entity) legal form - Content"
salience 1000
when
	$errorList : ErrorList()
	Section( $fields : field, $validateImport : validateImport  )
	Field( id == "legalForm", $fieldUsable : usable, $regex : format) from $fields
	eval($fieldUsable == true && StringUtils.isNotEmpty($regex))
	Representative(StringUtils.isNotEmpty(legalForm) &&
	          legalForm not matches $regex)
	$rulesInformation : RulesInformation($customObjects : customObjects )
then
	HashMap co = $customObjects;
	Boolean imported = co.get("imported");
	Boolean isSectionValidation = co.get("isSectionValidation");

	if ((imported == false || $validateImport == true) && isSectionValidation == false){
		addError("legalForm", "BRFormat", "This field has a bad format", null, $errorList);
	}else if((imported == false || $validateImport == true) && isSectionValidation == true){
		addError(null, "BR.representative.legalEntity.legalForm.Format", "The Legal Form field has a bad format", "mainForm.representativeDataSection", $errorList);
	}
end

rule "BR(legal entity) organization registration number  - Empty"
salience 1000
when
	$errorList : ErrorList()
	Section( $fields : field, $validateImport : validateImport  )
	Field( id == "businessVatNumber", $fieldUsable : usable, $fieldRequired : required ) from $fields
	eval($fieldUsable == true && $fieldRequired == true)
	Representative(identifiers  == null || (identifiers != null && identifiers.size()>0 && identifiers.get(0) != null && StringUtils.isEmpty(identifiers.get(0).value) == true))
	$rulesInformation : RulesInformation($customObjects : customObjects )
then
	HashMap co = $customObjects;
	Boolean imported = co.get("imported");
	Boolean isSectionValidation = co.get("isSectionValidation");

	if ((imported == false || $validateImport == true) && isSectionValidation == false){
		addError("businessVatNumber", "BRMandatory", "This field is mandatory", null, $errorList);
	}else if((imported == false || $validateImport == true) && isSectionValidation == true){
		addError(null, "BR.representative.legalEntity.registrationNumber.Empty", "The organization registration number field is mandatory", "mainForm.representativeDataSection", $errorList);
	}
end

rule "BR(legal entity) organization registration number - Content"
salience 1000
when
	$errorList : ErrorList()
	Section( $fields : field, $validateImport : validateImport  )
	Field( id == "businessVatNumber", $fieldUsable : usable, $regex : format) from $fields
	eval($fieldUsable == true && StringUtils.isNotEmpty($regex))
	Representative(identifiers != null,
	          identifiers.size() > 0,
	          $identifiers : identifiers)
	PersonIdentifier(value not matches $regex) from $identifiers
	$rulesInformation : RulesInformation($customObjects : customObjects )
then
	HashMap co = $customObjects;
	Boolean imported = co.get("imported");
	Boolean isSectionValidation = co.get("isSectionValidation");

	if ((imported == false || $validateImport == true) && isSectionValidation == false){
		addError("businessVatNumber", "BRFormat", "This field has a bad format", null, $errorList);
	}else if((imported == false || $validateImport == true) && isSectionValidation == true){
		addError(null, "BR.representative.legalEntity.registrationNumber.Format", "The organization registration number field has a bad format", "mainForm.representativeDataSection", $errorList);
	}
end

rule "BR812 (association name mandatory (association))"
salience 1000
when
	$errorList : ErrorList()
	Section( $fields : field, $validateImport : validateImport  )
	Field( id == "associationName", $fieldUsable : usable, $fieldRequired : required, $editableImportField : editableImport) from $fields
	eval($fieldUsable == true && $fieldRequired == true)
	Representative(representativeKind != null && (representativeKind.equals(RepresentativeKind.ASSOCIATION) ||representativeKind.equals(RepresentativeKind.LAWYER_ASSOCIATION)),
	        (name != null && StringUtils.isEmpty(name.organizationName) == true)  || (name==null))
	$rulesInformation : RulesInformation($customObjects : customObjects )
then
    HashMap co = $customObjects;
	Boolean imported = co.get("imported");
	Boolean isSectionValidation = co.get("isSectionValidation");
	if ((imported == false || $validateImport == true) && isSectionValidation == false){
	    addError("associationName", "BRMandatory", "This field is mandatory", null, $errorList);
	}else if((imported == false || $validateImport == true) && isSectionValidation == true){
        addError(null, "BR.representative.address.city.Empty", "The City field is mandatory", "mainForm.personalDataSection", $errorList);
    }
end

rule "BR Representative Email - Content"
salience 1000
when
    $errorList : ErrorList()
    Section( $fields : field, $validateImport : validateImport )
    Field( id == "email", $fieldUsable : usable, $regex : format ) from $fields
    $personRole : Representative($emails : emails, $representativeKind: representativeKind, $personKind: kind)
    Email(emailAddress != null && emailAddress != "" && emailAddress not matches $regex) from $emails
    $rulesInformation : RulesInformation($customObjects : customObjects)
then
    HashMap co = $customObjects;
    Boolean imported = co.get("imported");
	Boolean isSectionValidation = co.get("isSectionValidation");

    if ((imported == false || $validateImport == true || shouldValidateEmail($representativeKind, $personKind)) && isSectionValidation == false){
        addError("email", "BRFormat", "This field has a bad format",  null, $errorList);
    }else if((imported == false || $validateImport == true || shouldValidateEmail($representativeKind, $personKind)) && isSectionValidation == true){
        addError(null, "BR.person.email.Format", "The Email field has a bad format.", "mainForm.representativeDataSection", $errorList);
        addError(null, $personRole.name.fullName, $personRole.name.fullName, "mainForm.representativeDataSection", $errorList);
    }
end

function boolean shouldValidateEmail(RepresentativeKind kind, PersonKind personKind){
    if(kind == null || personKind == null){
        return true;
    }
    if(kind == RepresentativeKind.ASSOCIATION ||
        (kind == RepresentativeKind.OTHER &&
            (personKind == PersonKind.LEGAL_ENTITY || personKind == PersonKind.NATURAL_PERSON))){
            return false;
    } else {
        return true;
    }
}

rule "BR Representative POW validity end date - Content"
salience 1000
when
    $errorList : ErrorList()
    Section( $fields : field)
    Field( id == "powValidityEndDate", $fieldUsable : usable, $editableImportField : editableImport) from $fields
    eval($fieldUsable == true && $editableImportField == true)
    Representative($powValidityEndDate : powValidityEndDate, powValidityEndDate != null)
    $rulesInformation : RulesInformation($customObjects : customObjects)
then
    HashMap co = $customObjects;
	Boolean isSectionValidation = co.get("isSectionValidation");
	Date currentDate = new Date();

	if(currentDate.compareTo($powValidityEndDate) > 0){
        if (isSectionValidation == false){
            addError("powValidityEndDate", "BR.powValidityEndDate", "POW validity date can not be in the past",  null, $errorList);
        }else if(isSectionValidation == true){
            addError(null, "BR.powValidityEndDate", "POW validity date can not be in the past", "mainForm.representativeDataSection", $errorList);
        }
    }
end

rule "BR pow validity end date - Empty"
salience 1000
when
	$errorList : ErrorList()
	Section( $fields : field )
	Field( id == "powValidityEndDate", $fieldUsable : usable ) from $fields
	Field( id == "powValidityIndefiniteIndicator", $fieldIndicatorUsable : usable ) from $fields
	Representative(powValidityEndDate==null && (powValidityIndefiniteIndicator == null || powValidityIndefiniteIndicator == false))
	eval($fieldUsable == true && $fieldIndicatorUsable == true)
	$rulesInformation : RulesInformation($customObjects : customObjects )
then
	HashMap co = $customObjects;
	Boolean imported = co.get("imported");
	Boolean isSectionValidation = co.get("isSectionValidation");

	if (isSectionValidation == false){
		addError("powValidityEndDate", "BR.Enter.Date.Or.Select.Indefinite", "This field is mandatory", null, $errorList);
	}
end

rule "BR pow validity end date - NOT Empty"
salience 1000
when
	$errorList : ErrorList()
	Section( $fields : field )
	Field( id == "powValidityEndDate", $fieldUsable : usable ) from $fields
	Field( id == "powValidityIndefiniteIndicator", $fieldIndicatorUsable : usable ) from $fields
	Representative(powValidityEndDate !=null && (powValidityIndefiniteIndicator != null && powValidityIndefiniteIndicator == true))
	eval($fieldUsable == true && $fieldIndicatorUsable == true)
	$rulesInformation : RulesInformation($customObjects : customObjects )
then
	HashMap co = $customObjects;
	Boolean imported = co.get("imported");
	Boolean isSectionValidation = co.get("isSectionValidation");

	if (isSectionValidation == false){
		addError("powValidityEndDate", "BR.Must.Not.Have.Date.For.Indefinite", "You must not fill in validity end date if the POA is indefinite", null, $errorList);
	}
end

rule "BR pow reauthorization indicator"
salience 1000
when
	$errorList : ErrorList()
	Section( $fields : field )
	Field( id == "powReauthorizationIndicator", $fieldUsable : usable) from $fields
	eval($fieldUsable == true)
	Representative(powReauthorizationIndicator == null)
	$rulesInformation : RulesInformation($customObjects : customObjects )
then
	HashMap co = $customObjects;
	Boolean imported = co.get("imported");
	Boolean isSectionValidation = co.get("isSectionValidation");

	if (isSectionValidation == false){
		addError("powReauthorizationIndicator", "BRMandatory.Select.One", "This field is mandatory", null, $errorList);
	}
end